-- Run this in the Supabase SQL Editor to set up your tables

-- 1. Projects
CREATE TABLE IF NOT EXISTS projects (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    budget_total numeric default 0,
    start_date date,
    end_date date,
    status text default 'Activo',
    latitude numeric default -33.4489,
    longitude numeric default -70.6693
);

-- 2. Users
CREATE TABLE IF NOT EXISTS users (
    id bigint generated by default as identity primary key,
    username text unique not null,
    password_hash text not null,
    full_name text,
    role text not null
);

-- UPDATE: Add email column for notifications (Run if not exists)
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT;

-- 3. Project Assignments
CREATE TABLE IF NOT EXISTS project_assignments (
    id bigint generated by default as identity primary key,
    project_id bigint references projects(id),
    user_id bigint references users(id),
    role text, 
    assigned_at timestamptz default now()
);

-- 4. Tenders (Licitaciones)
CREATE TABLE IF NOT EXISTS tenders (
    id bigint generated by default as identity primary key,
    project_id bigint references projects(id),
    title text not null,
    type text not null,
    budget_estimated numeric,
    utm_value_at_creation numeric,
    status text default 'Borrador',
    ssd_code text,
    created_at timestamptz default now()
);

-- 5. Contracts
CREATE TABLE IF NOT EXISTS contracts (
    id bigint generated by default as identity primary key,
    tender_id bigint references tenders(id),
    contractor_name text,
    rut_contractor text,
    amount numeric,
    start_date date,
    end_date date,
    status text default 'Activo'
);

-- 6. Guarantees
CREATE TABLE IF NOT EXISTS guarantees (
    id bigint generated by default as identity primary key,
    contract_id bigint references contracts(id),
    type text,
    amount numeric,
    expiration_date date,
    status text default 'Vigente',
    scanned_doc_path text
);

-- 7. Purchase Orders (Finance)
CREATE TABLE IF NOT EXISTS purchase_orders (
    id bigint generated by default as identity primary key,
    project_id bigint references projects(id),
    contract_id bigint references contracts(id), -- Nullable
    provider_name text,
    date date,
    total_amount numeric,
    description text,
    status text default 'Pendiente'
);

-- 8. Subcontractors (Compliance)
CREATE TABLE IF NOT EXISTS subcontractors (
    id bigint generated by default as identity primary key,
    rut text unique,
    name text not null,
    contact_email text,
    status text default 'Activo'
);

-- 9. Quality Logs
CREATE TABLE IF NOT EXISTS quality_logs (
    id bigint generated by default as identity primary key,
    project_id bigint references projects(id),
    title text,
    description text,
    inspector_name text,
    date timestamptz default now(),
    status text default 'Pendiente'
);

-- 10. Faenas (Legacy/Aux)
CREATE TABLE IF NOT EXISTS faenas (
    id bigint generated by default as identity primary key,
    project_id bigint references projects(id),
    name text not null,
    supervisor text
);

-- 11. Units (Legacy/Aux)
CREATE TABLE IF NOT EXISTS units (
    id bigint generated by default as identity primary key,
    name text not null,
    type text,
    details text
);

-- 12. Expenses
CREATE TABLE IF NOT EXISTS expenses (
    id bigint generated by default as identity primary key,
    date date not null,
    project_id bigint references projects(id),
    faena_id bigint references faenas(id),
    unit_id bigint references units(id),
    category text,
    amount numeric not null,
    description text,
    evidence_path text
);

-- 13. Tasks (Lean)
CREATE TABLE IF NOT EXISTS tasks (
    id bigint generated by default as identity primary key,
    project_id bigint references projects(id),
    name text not null,
    start_date date,
    end_date date,
    type text,
    status text default 'To Do',
    tags text
);

-- 14. Phases
CREATE TABLE IF NOT EXISTS phases (
    id bigint generated by default as identity primary key,
    project_id bigint references projects(id),
    name text,
    start_date date,
    end_date date,
    status text default 'Pendiente'
);

-- 15. Comments
CREATE TABLE IF NOT EXISTS comments (
    id bigint generated by default as identity primary key,
    project_id bigint references projects(id),
    user_id bigint references users(id),
    content text,
    timestamp timestamptz default now()
);

-- Admin & Config
DROP TABLE IF EXISTS system_config;
CREATE TABLE system_config (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS ai_usage_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  tokens_used INT DEFAULT 0,
  usage_date DATE DEFAULT CURRENT_DATE,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
