
print("COPIA Y EJECUTA EL SIGUIENTE SQL EN EL EDITOR SQL DE SUPABASE:")
print("-" * 50)
print("""
-- 1. Enhance Subcontractors Table
ALTER TABLE subcontractors ADD COLUMN specialty TEXT;
ALTER TABLE subcontractors ADD COLUMN contact_phone TEXT;
ALTER TABLE subcontractors ADD COLUMN representative TEXT;

-- 2. Create Compliance Documents Table
CREATE TABLE compliance_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcontractor_id BIGINT REFERENCES subcontractors(id) ON DELETE CASCADE,
    document_type TEXT NOT NULL, -- 'F30', 'F30-1', 'Carpeta Arranque', etc.
    status TEXT DEFAULT 'Pendiente', -- 'Vigente', 'Vencido', 'Pendiente'
    expiration_date DATE,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
""")
print("-" * 50)
