
print("COPIA Y EJECUTA EL SIGUIENTE SQL EN EL EDITOR SQL DE SUPABASE:")
print("-" * 50)
print("""
-- 1. Create Budget Items Table
CREATE TABLE budget_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
    item_name TEXT NOT NULL,
    category TEXT, -- 'Materiales', 'Mano de Obra', 'Subcontratos', 'Equipos', 'General'
    estimated_amount NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
""")
print("-" * 50)
