
print("COPIA Y EJECUTA EL SIGUIENTE SQL EN EL EDITOR SQL DE SUPABASE:")
print("-" * 50)
print("""
-- 1. Create Lab Tests Table
CREATE TABLE lab_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
    test_type TEXT NOT NULL, -- 'Hormigón', 'Suel', 'Acero', etc.
    test_date DATE,
    result TEXT, -- 'Aprobado', 'Rechazado', 'Pendiente'
    observation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
""")
print("-" * 50)
